DO $$ BEGIN
   IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'spawd') THEN
      CREATE ROLE spawd WITH LOGIN PASSWORD ${POSTGRES_PASSWORD};
      ALTER ROLE spawd WITH SUPERUSER CREATEDB CREATEROLE;
   END IF;
CREATE DATABASE vyrtuous;
